version: '3.8'
services:
  web:
    image: php:apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: davy123
      MYSQL_DATABASE: davy
      MYSQL_USER: davy
      MYSQL_PASSWORD: davy123

  phpmyadmin:
    image: phpmyadmin/phpmyadmin # The official phpMyAdmin Docker image
    links:
      - db:mysql # Links phpMyAdmin to your 'db' service, aliasing it as 'mysql' within phpMyAdmin
    environment:
      PMA_HOST: db # phpMyAdmin will connect to the 'db' service (aliased as 'mysql')
      PMA_PORT: 3306 # Default MySQL port
      MYSQL_ROOT_PASSWORD: i5Y6LiyKsyG72ES # Use your root password for phpMyAdmin to connect
      # If you want to use the 'davy' user for phpMyAdmin, you can specify:
      # PMA_USER: davy
      # PMA_PASSWORD: davy123
    ports:
      - "8080:80" # This maps port 8080 on your host to port 80 in the phpMyAdmin container
    restart: always

# Define the named volume at the top level
volumes:
  db_data: # This declares a named volume called 'db_data'. Docker will manage its location on your host.
